### ISSUE TITLE
Support GitLab plugin GitLab API token credential type

### ISSUE THREAD

**Issue by ite-jankl** [jenkinsci/violation-comments-to-gitlab-plugin#22]
When the GitLab plugin is installed, a credential category for personal API tokens is available.

This plugin could then make use of this more specific one instead of the generic "secret text" category.

At the moment it does not support GitLab API token credentials at all.

**Comment by tomasbjerre** [comment]
To clarify, GitLab API token can be specified from a credential or with just a string:
```
  // Specify one of these
  apiToken: '6xRcmSzPzzEXeS2qqr7R',
  apiTokenCredentialsId: 'id',
```

In order to support the credential category used by the GitLab plugin I think [a dependency](https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/connection/GitLabApiToken.java) is needed on that plugin. I don't want to add such a dependency.

The Gitlab plugin is terribly maintained. Look at the open issues and the PR:s. Even if it was better supported I would not recommend anyone to use it. I think it is overly complex. And I would recommend the simpler [generic webhook](https://github.com/jenkinsci/generic-webhook-trigger-plugin/) instead. 

As there are many ways of integrating GitLab with Jenkins, it does not make sense to have this plugin depend on one of them.

Adding a dependency would polute the classpath of this plugin.
